data_dir: /kaggle/working/input/child-mind-institute-detect-sleep-states
processed_dir: /kaggle/working/kami/processed
output_dir: /kaggle/working/kami/output
model_dir: /kaggle/working/kami/output/train
cv_model_dir: /kaggle/working/kami/output/cv_train
kami_dir: /kaggle/working/kami
input_dir: /kaggle/working/input
sub_dir: ./