data_dir: /root/app/input/
processed_dir: /root/app/kami/processed
output_dir: /root/app/kami/output
model_dir: /root/app/kami/output/train
cv_model_dir: /root/app/kami/output/cv_train
kami_dir: /root/app/kami
input_dir: /root/app/input
sub_dir: ./
